### ISSUE TITLE
Cannot read property 'runtime' of undefined

### ISSUE THREAD

**Issue by cainiaokan** [detrohutt/babel-plugin-import-graphql#37]
version 2.5.1

Got an error trying to start my node server.
According to the output, the `options` object is undefined.
I suppose we should check the `options` object before referencing its properties.

/Users/apple/Code/zhiyin-open-web/node_modules/babel-plugin-import-graphql/build/index.js:51
      if (options.runtime) {
                  ^

TypeError: Cannot read property 'runtime' of undefined
    at Plugin.manipulateOptions (/Users/apple/Code/zhiyin-open-web/node_modules/babel-plugin-import-graphql/build/index.js:51:19)
    at File.buildPluginsForOptions (/Users/apple/Code/zhiyin-open-web/node_modules/babel-core/lib/transformation/file/index.js:280:16)
    at new File (/Users/apple/Code/zhiyin-open-web/node_modules/babel-core/lib/transformation/file/index.js:146:11)
    at Pipeline.transform (/Users/apple/Code/zhiyin-open-web/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Object.transformFileSync (/Users/apple/Code/zhiyin-open-web/node_modules/babel-core/lib/api/node.js:152:10)
    at compile (/Users/apple/Code/zhiyin-open-web/node_modules/babel-register/lib/node.js:118:20)
    at loader (/Users/apple/Code/zhiyin-open-web/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/apple/Code/zhiyin-open-web/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)

**Comment by detrohutt** [comment]
Already on it again lol. Try `v2.5.2`. I moved the dependency check into the visitor function where it's easier to access the options.

**Comment by cainiaokan** [comment]
I can confirm it did solve my problem.  Thx for saving my day~

**Comment by detrohutt** [comment]
Thanks for starring my plugin! 😄
